name: Build

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "main"
      - "fix-cve"

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.1"

      - name: Prepare things
        id: prepare
        run: |
          mkdir artifacts

          # Extract version from tag
          VERSION=$(git tag --points-at HEAD | head -n1)
          if [[ "$VERSION" != "" ]]; then
            echo "Release $VERSION of ${{ github.sha }}" > RELEASE.txt
            echo >> RELEASE.txt
          fi

      - name: Install dependencies
        run: |
          go get github.com/akavel/rsrc
          go get -u honnef.co/go/tools/cmd/staticcheck
          go get -u github.com/kisielk/errcheck
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

      - name: Build
        run: |
          bash travis-build.sh

      # - name: Build
      #   run: |
      #     GOARCH=${GOARCH} GOOS=${GOOS} go build -o artifacts/parse-template-${GOOS}-${GOARCH}${EXT} cmd/parse-template.go
      #   env:
      #     GOOS: ${{ matrix.target.os }}
      #     GOARCH: ${{ matrix.target.platform }}
      #     EXT: ${{ matrix.target.os == 'windows' && '.exe' || '' }}

      # # TODO: macOS build

      # - name: Archive build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifacts
      #     path: |
      #       artifacts

      # # Release tagged pushes
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     body_path: RELEASE.txt
      #     files: artifacts/*
